---
- name: add JDK_HOME to the default environment...
  become: yes
  become_user: root
  with_items:
    - f: oracle-jdk.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
